---
# ==============================================================================
# INFRASTRUCTURE DEPLOYMENT
# ==============================================================================

- name: System-Level Setup
  hosts: all
  become: yes
  vars_files:
    - config.yml
    - vault.yml
  roles:
    - common

- name: Public Instance Dependencies
  hosts: public_instances
  become: yes
  vars_files:
    - config.yml
    - vault.yml
  roles:
    - aws_cli

- name: Deploy Public Services
  hosts: public_instances
  become: no
  vars_files:
    - config.yml
    - vault.yml
  roles:
    - rmqtt
    - api
    - nginx

- name: Deploy Private Services
  hosts: private_instances
  become: no
  vars_files:
    - config.yml
    - vault.yml
  roles:
    - redis
