# local-config.yml
oci_bastion_ip: "Public Server IP"
oci_private_ip: "Private Server IP"

# KhamoshChat API - Google OAuth
khamoshchat_google_client_id: "google oauth client id"
khamoshchat_google_redirect_uri: "http://localhost:3000/register/oauth/google/callback"

# Let's Encrypt Automation
letsencrypt_email: "your email for registration"
domain_name: "your domain"
