---
- name: Ensure user systemd container directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/containers/systemd"
    state: directory
    mode: '0755'

- name: Create DeezChatz Podman Network Quadlet
  ansible.builtin.copy:
    dest: "{{ ansible_facts['user_dir'] }}/.config/containers/systemd/deezchatz.network"
    content: |
      [Network]
      NetworkName=deezchatz
    mode: '0644'
